Logger
CachedNerds/Toolbox pull request #18
Opened 2017-07-10 00:31 UTC by DannyPeck

Redesigned Conversion::Variant and Conversion::VariantVisitor into a Result class with a Variant typedef inside (Result::Variant) and an internal protected VariantVisitor class.  Finished writing Unit Tests for the Logger system and all of its subsystems.

2017-07-10 18:12 UTC, technetos commented
in ```ConvertableTo``` the ```convert``` method is overkill and is implementing something that is inherently already part of c++.  

```convert``` should be replace with the following conversion function:

```virtual const operator ResultType (void) const = 0;```

The above declares a conversion function for the implicit conversion from what ever implements the ```ConvertableTo``` interface to what ever type ```ResultType``` is

2017-07-10 18:32 UTC, technetos commented
The variant isn't necessary.  The compiler is going to try exact type candidates first, then it will try implicit conversion candidates if no exact candidates are found.  We don't need to explicitly setup infrastructure that expects an either-or scenario, C++ does this already.

2017-07-10 18:51 UTC, technetos requested changes
See my comments on the PR

2017-07-11 00:42 UTC, technetos approved these changes

2017-07-14 05:05 UTC, xmclark reviewed
I'm cool with this.

2017-07-14 05:05 UTC, xmclark commented on C++/Logger/makefile
> +CC = g++
Thank you for allowing the compiler to be easily configurable in make.

2017-07-14 05:05 UTC, xmclark commented on C++/Logger/TypeIs.h
> +struct TypeIs
Is this our preferred naming convention for template metafunctions? The old way was more akin to the STL style which I prefer, but the PascalCase is fine. 

EDIT: I see in the previous comit that you mention this is the preferred style for the project.

2017-07-14 06:20 UTC, DannyPeck commented on C++/Logger/TypeIs.h
> +struct TypeIs
I know we stated the preferred style for the project but I am inclined to agree with you for template metafunctions.

2017-07-14 22:06 UTC, technetos commented
Approved!

2017-07-14 22:08 UTC, technetos commented on C++/Logger/TypeIs.h
> +struct TypeIs
I too prefer `type_is`; I was conforming to the style of the existing code base, shall I switch it back?

2017-07-14 22:16 UTC, technetos commented on C++/Logger/TypeIs.h
> +struct TypeIs
Also how do you want to name the files themselves? `TypeIs.h` or `type_is.h`

2017-07-15 04:02 UTC, merged