Add zenhub documentation
CachedNerds/Toolbox pull request #36
Opened 2017-07-16 18:36 UTC by xmclark

### Changes proposed within this pull request:
- Add zenhub documentation to Contributing.md
- Remove filler in Contributing.md
-

2017-07-17 13:06 UTC, DannyPeck requested changes
Looks great!  Just one note about Milestones :)

2017-07-17 13:06 UTC, DannyPeck commented on .github/CONTRIBUTING.md
> +ZenHub also adds Milestones and Epics. Milestones are used for releases or features. Epics track larger development efforts which may span multiple releases.
Milestones are actually provided by Github in vanilla-Github.  I would still keep how we plan to use them in here though.

2017-07-17 13:06 UTC, DannyPeck commented on .github/CONTRIBUTING.md
> +ZenHub is highly suggested for contributors because it allows one to see more information about issues, milestones, and epics that are not avaialble in vanilla-GitHub.
See milestone comment above.

2017-07-21 03:56 UTC, xmclark commented
I've addressed the issue about the milestones. Will merge when codacy is done.

2017-07-21 04:09 UTC, DannyPeck approved these changes

2017-07-21 04:42 UTC, merged