Created C++ Coding Standard Page
CachedNerds/Toolbox pull request #37
Opened 2017-07-19 02:22 UTC by DannyPeck

### Changes proposed within this pull request:
- Started the C++ Code Standard Documentation

2017-07-21 21:42 UTC, technetos commented
```
if (condition)
{

}
```

2017-07-21 21:44 UTC, technetos commented on C++/CodingStandard.md
> +{
```
if (condition)
{

}
```

2017-07-21 21:44 UTC, technetos requested changes
See my comment

2017-07-21 21:57 UTC, DannyPeck commented on C++/CodingStandard.md
> +{
Fair enough

2017-07-21 22:07 UTC, technetos commented on C++/CodingStandard.md
> +{
That was all.

2017-07-21 22:15 UTC, technetos commented
Does this document serve as a standard for comments / doxycomments aswell?

2017-07-21 23:44 UTC, xmclark commented
@technetos yeah seems like a good place to put that kind of stuff.

2017-07-24 02:03 UTC, xmclark requested changes
I've added some more content and changed the formatting.

2017-07-27 07:02 UTC, xmclark commented
Does this need anything else? I have moved it to done.

2017-07-27 07:03 UTC, DannyPeck commented
I say go ahead and merge it and if we need to add to it we will.

2017-08-05 22:39 UTC, merged